"""all tables

Revision ID: 0aef1df2acdf
Revises: 
Create Date: 2018-06-24 13:54:49.944061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aef1df2acdf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=100), nullable=True),
    sa.Column('dev_lead', sa.String(length=100), nullable=True),
    sa.Column('developers', sa.String(length=100), nullable=True),
    sa.Column('sprint_number', sa.String(length=300), nullable=True),
    sa.Column('task_name', sa.String(length=100), nullable=True),
    sa.Column('task_desc', sa.String(length=1000), nullable=True),
    sa.Column('user_story_id', sa.String(length=100), nullable=True),
    sa.Column('project_id', sa.String(length=100), nullable=True),
    sa.Column('project_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
