"""new flaskdb database

Revision ID: 95dd3669966c
Revises: 
Create Date: 2018-04-05 21:31:16.080872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95dd3669966c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dm_seq', sa.String(length=100), nullable=True),
    sa.Column('data_type', sa.String(length=100), nullable=True),
    sa.Column('schema', sa.String(length=100), nullable=True),
    sa.Column('db_object', sa.String(length=100), nullable=True),
    sa.Column('frequency', sa.String(length=100), nullable=True),
    sa.Column('data_provider', sa.String(length=100), nullable=True),
    sa.Column('providing_system', sa.String(length=100), nullable=True),
    sa.Column('interface', sa.String(length=100), nullable=True),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('data_retention', sa.String(length=100), nullable=True),
    sa.Column('latency', sa.String(length=100), nullable=True),
    sa.Column('data_in_qa0', sa.String(length=100), nullable=True),
    sa.Column('row_count_per_period', sa.String(length=100), nullable=True),
    sa.Column('active_in_prod', sa.String(length=100), nullable=True),
    sa.Column('order_by', sa.String(length=100), nullable=True),
    sa.Column('segment_by', sa.String(length=100), nullable=True),
    sa.Column('special_notes', sa.String(length=1000), nullable=True),
    sa.Column('project_id', sa.String(length=100), nullable=True),
    sa.Column('project_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=100), nullable=True),
    sa.Column('pid', sa.String(length=100), nullable=True),
    sa.Column('pmt', sa.String(length=100), nullable=True),
    sa.Column('dev_lead', sa.String(length=100), nullable=True),
    sa.Column('developers', sa.String(length=100), nullable=True),
    sa.Column('release', sa.String(length=100), nullable=True),
    sa.Column('sprint_schedule', sa.String(length=300), nullable=True),
    sa.Column('lpm', sa.String(length=100), nullable=True),
    sa.Column('pm', sa.String(length=100), nullable=True),
    sa.Column('scrum_master', sa.String(length=100), nullable=True),
    sa.Column('se', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=10000), nullable=True),
    sa.Column('impact', sa.String(length=100), nullable=True),
    sa.Column('readiness_status', sa.String(length=100), nullable=True),
    sa.Column('deployment_cr', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('project')
    op.drop_table('db_object')
    # ### end Alembic commands ###
