"""removed user foreign key in Project table

Revision ID: c2db736a3903
Revises: cee75e964948
Create Date: 2018-04-05 20:44:08.315926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2db736a3903'
down_revision = 'cee75e964948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('project_user_id_fkey', 'project', type_='foreignkey')
    op.drop_column('project', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('project_user_id_fkey', 'project', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
