"""comment out the follower and post models

Revision ID: cee75e964948
Revises: 54b07054cbf8
Create Date: 2018-04-05 20:18:17.096821

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cee75e964948'
down_revision = '54b07054cbf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post_timestamp', table_name='post')
    op.drop_table('post')
    op.drop_table('db_object_tmp')
    op.drop_table('followers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('followed_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], name='followers_followed_id_fkey'),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], name='followers_follower_id_fkey')
    )
    op.create_table('db_object_tmp',
    sa.Column('dm_seq', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('data_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('schema', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('db_object', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('frequency', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('data_provider', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('providing_system', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('interface', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('topic', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('data_retention', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('latency', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('data_in_qa0', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('row_count_per_period', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('active_in_prod', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('order_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('segment_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('special_notes', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('project_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True)
    )
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=140), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='post_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='post_pkey')
    )
    op.create_index('ix_post_timestamp', 'post', ['timestamp'], unique=False)
    # ### end Alembic commands ###
