"""add columns to project, remove unique constraint from pid

Revision ID: 54b07054cbf8
Revises: 
Create Date: 2018-04-04 10:52:07.525916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54b07054cbf8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=100), nullable=True),
    sa.Column('pid', sa.String(length=100), nullable=True),
    sa.Column('pmt', sa.String(length=100), nullable=True),
    sa.Column('dev_lead', sa.String(length=100), nullable=True),
    sa.Column('developers', sa.String(length=100), nullable=True),
    sa.Column('release', sa.String(length=100), nullable=True),
    sa.Column('sprint_schedule', sa.String(length=100), nullable=True),
    sa.Column('lpm', sa.String(length=100), nullable=True),
    sa.Column('pm', sa.String(length=100), nullable=True),
    sa.Column('scrum_master', sa.String(length=100), nullable=True),
    sa.Column('se', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=10000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('impact', sa.String(length=100), nullable=True),
    sa.Column('readiness_status', sa.String(length=100), nullable=True),
    sa.Column('deployment_cr', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    # ### end Alembic commands ###
